name: Run HubSpot Script

on:
  push:
    branches:
      - main

  schedule:
    - cron: '50 0 * * *'  # Ejecutar a las 12:50 AM UTC todos los días (7:50 PM UTC-5)

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Utilizar Python 3.10

    - name: Clean pip cache
      run: python -m pip cache purge

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Copy service account key
      run: |
        mkdir -p ~/.google/
        echo "${{ secrets.GOOGLE_CREDENTIALS }}" > ~/.google/service-account-file.json

    - name: Run script
      run: python script_export.py
